import "../../styles/globals.css";

import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import { GuestTracker } from "../../components/GuestTracker";
import Header from "../../components/site/layout/header/Header";
import Footer from "../../components/site/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen space-y-20" dir="rtl">
        <Header />

        <GuestTracker />
        <main className="flex-grow">{children}</main>
        <Toaster position="top-center" />

        <Footer />
      </body>
    </html>
  );
}
