import "../styles/globals.css";

import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { GuestTracker } from "../components/GuestTracker";
import CheckUser from "../lib/check/Check";
import SessionAuth from "../components/common/SessionAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await CheckUser();
  return (
    <html lang="fa">
      <body dir="rtl">
        {!token && <SessionAuth />}
        <GuestTracker />
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
