import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "../components/layout/header/Header";
import Footer from "../components/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" dir="rtl">
      <body className="flex flex-col min-h-screen space-y-10">
=======
    <html lang="en">
      <body className="flex flex-col min-h-screen" dir="rtl">
>>>>>>> 8744c8fc7718c136d9a679a70490ef5de95b35f3
        <Header />

        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
